Expand the code with 100 Prisoners simulation
jaredkotoff/100Doors pull request #2
Opened 2023-10-27 12:41 UTC by y9rabbito

This is regarding the issue #1, Implemented 100 prisoners simulation, @jaredkotoff could you please take ur time and check it whether it can be merged or not.

2023-10-28 03:10 UTC, jaredkotoff requested changes

2023-10-28 03:10 UTC, jaredcat commented on 100Doors.py
> +        monty_hall(doors, enable_auto, total_games, always_switch="n")
The user is never asked if about the `always_switch` flag so its always `n`. This currently creates incorrect output where it says that they've "always switched" but the odds of winning are for never switching

<img width="287" alt="Screenshot 2023-10-27 at 5 50 45 PM" src="https://github.com/jaredkotoff/100Doors/assets/3268576/a69f9b9f-26b1-494f-8989-a8dc050e3703">

So, 1. ask the user if they want to "always switch" or not
2. make sure the output text matches this flag

2023-10-28 03:31 UTC, jaredkotoff requested changes

2023-10-28 03:31 UTC, jaredkotoff commented on 100Doors.py
> +                break
I dont think this simulates the problem correctly. There shuold be no random picking of boxes.
I would recommend watching the Veritasium video i linked in the issue.

2023-10-28 03:31 UTC, jaredkotoff commented on 100Doors.py
> +        total_games = int(input("How many 100 Prisoners games to simulate: "))
```suggestion
        total_games = int(input("How many \"100 Prisoners\" games to simulate: "))
```

2023-10-28 03:31 UTC, jaredkotoff commented on 100Doors.py
> +        number_loops = int(input("Enter the number of loops (e.g., 50): "))
```suggestion
        number_loops = int(input("Enter the number of loops (default: 50): "))
```

2023-10-28 03:31 UTC, jaredkotoff commented on 100Doors.py
> +def prisoners_simulation(total_games, number_loops):
```suggestion
def prisoners_simulation(total_games=1, number_loops=50):
```

2023-10-28 06:14 UTC, y9rabbito commented on 100Doors.py
> +def prisoners_simulation(total_games, number_loops):
okk @jaredkotoff i will take care of that.

2023-10-29 04:29 UTC, y9rabbito commented
@jaredkotoff could you please run it and see it if the changes are made correctly, i myself implemented some new codes.

2023-10-29 19:07 UTC, jaredkotoff commented on 100Doors.py
> +        print("\nChoose a strategy you want to simulate the 100Doors:")
Typo here

```suggestion
        print("\nChoose a strategy you want to simulate the \"100 Prisoners Problem\":")
```

2023-10-29 19:55 UTC, jaredkotoff requested changes
Very good changes. All the statistics seem to make sense now. But lets not use external libs. This is mean to be an easy/fun way to see how these unintuitive problems play out with large numbers and should be very easy to run

2023-10-29 19:55 UTC, jaredkotoff commented on 100Doors.py
> +        print("\nChoose a strategy you want to simulate the 100Doors:")
Typo here

```suggestion
        print("\nChoose a strategy you want to simulate the \"100 Prisoners Problem\":")
```

2023-10-29 19:55 UTC, jaredkotoff commented on 100Doors.py
> +            number_loops = int(number_loops)
```suggestion
            number_loops = int(number_loops or 50)
```

2023-10-29 19:55 UTC, jaredkotoff commented on 100Doors.py
> +        number_loops = "50"
Not needed
```suggestion
```

2023-10-29 19:55 UTC, jaredkotoff commented on 100Doors.py
> +        while not (strategy.isdigit() and 0 < int(strategy)):
nit/opinion
```suggestion
        options = [1,2]
        while not (strategy.isdigit() and int(strategy) in options):
```

2023-10-29 19:55 UTC, jaredkotoff commented on 100Doors.py
> +BOX_NUMBERS = [x for x in range(0,100)]
nit: don't like these global variables that are only used for part of the execution path

2023-10-29 19:55 UTC, jaredkotoff commented on 100Doors.py
> +import numpy as np
nit: rather not use external lib that requires people to install it. 
suggestion below

2023-10-29 19:55 UTC, jaredkotoff commented on 100Doors.py
> +    prisoners_choices = np.random.choice(BOX_NUMBERS,size=50,replace=False)
`boxes` here is already randomly shuffled. Lets just look at the first 50 boxes and see if the prisoner's number is in them. This will let us remove `numpy` lib

This also better simulates the problem since we're "looking" into our boxes rather than "cheating" and just creating a new random number list.

2023-10-29 19:55 UTC, jaredkotoff commented on 100Doors.py
> +                enable_auto = input("Would you like to see autoplay?(y\\n): ").lower()
nit
```suggestion
                enable_auto = input("Would you like to see autoplay? (y\\n): ").lower()
```

2023-10-29 19:55 UTC, jaredkotoff commented on 100Doors.py
> +                switch = input("Always switch doors?(y\\n): ")
nit
```suggestion
                switch = input("Always switch doors? (y\\n): ")
```

2023-10-29 19:55 UTC, jaredkotoff commented on 100Doors.py
> +                    keep_playing = input("Would you like to keep playing?(y\\n): ").lower()
nit
```suggestion
                    keep_playing = input("Would you like to keep playing? (y\\n): ").lower()
```

2023-10-30 04:23 UTC, y9rabbito commented on 100Doors.py
> +    prisoners_choices = np.random.choice(BOX_NUMBERS,size=50,replace=False)
@jaredkotoff but this BOX_NUMBERS are list of 0..99, which is not shuffled and for everyman if it's not change then they will select the same 50 numbers from begining.

2023-10-30 04:36 UTC, jaredkotoff commented on 100Doors.py
> +    prisoners_choices = np.random.choice(BOX_NUMBERS,size=50,replace=False)
yea thats why im saying to use `boxes`

2023-10-30 05:18 UTC, y9rabbito commented
@jaredkotoff can u just look the code i have changed it according to this. Could you please review it and accept the pr merge within 10 hours so it can be counted on hacktoberfest.

2023-10-30 05:29 UTC, jaredkotoff approved these changes

2023-10-30 05:29 UTC, merged

2023-10-30 05:41 UTC, jaredkotoff commented
@y9rabbito  Nice job. Thanks for your contribution. Hope you had fun and learn something!

2023-10-30 11:28 UTC, y9rabbito commented
Thank you sir @jaredkotoff I really learn lot of things from this project like new code style, how to write efficient codes some syntax which helps to reduce lines, I am thankfull to you. I also wanted if you have time you could really give some material or teach me about complex project structures and how real world projects are build like those are hosted in github written in c++,python or anyother language and the structure of the projects(i.e different folders)